import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { Roboto } from 'next/font/google';
import { ThemeProvider } from '@mui/material/styles';
import theme from "@/theme/theme";

import '../styles/global/scssReset.css';
import styles from '../styles/mainLayout/container.module.scss';
import globalStyles from '../styles/global/globals.module.scss';

const roboto = Roboto({
    weight: ['300', '400', '500', '700'],
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-roboto',
});


import Sidebar from "@/components/Sidebar/Sidebar";
import StoreProvider from "@/app/StoreProvider";
import Header from "@/components/Header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    const sidebarLinks = [
            {link: "/candidates", text: "Candidates"},
            {link: "/settings", text: "Settings"},
            {link: "/about", text: "About"},
        ]
  return (
    <html lang="en">
      <body className={globalStyles.body}>
      <AppRouterCacheProvider options={{ enableCssLayer: false }}>
        <ThemeProvider theme={theme}>
            <StoreProvider>
                <div className={styles.container}>
                    <Sidebar sidebarLinks={sidebarLinks} />
                    <Header />
                    {children}
                </div>
            </StoreProvider>
            <div id="modal" />
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
